-- Create units_offices table for non-teaching staff
CREATE TABLE IF NOT EXISTS units_offices (
    id INT AUTO_INCREMENT PRIMARY KEY,
    unit_name VARCHAR(255) NOT NULL,
    display_order INT DEFAULT 0,
    is_active TINYINT(1) DEFAULT 1,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Insert all units/offices/directorates
INSERT INTO units_offices (unit_name, display_order) VALUES
('Office of the Vice Chancellor', 1),
('Office of the Deputy Vice-Chancellor Admin.', 2),
('Office of the Deputy Vice-Chancellor University Development Services', 3),
('Office of the Deputy Vice-Chancellor Academics', 4),
('Bursary Department', 5),
('Tetfund Office', 6),
('Office of The Registrar', 7),
('Establishment Division', 8),
('Open Registry', 9),
('Central Admin. & Council Matters', 10),
('Internal Audit Unit', 11),
('Directorate of Int\'L Collaboration & Affiliation', 12),
('Fire Service Unit', 13),
('I.D Card Unit', 14),
('ICT', 15),
('Information and Publication Unit', 16),
('CBT', 17),
('IDELL', 18),
('Security Division', 19),
('Liaison Office', 20),
('University Library', 21),
('Centre for Entrepreneurship Training & Consultancy Services', 22),
('Advancement Unit', 23),
('Endowment Unit', 24),
('GST Unit', 25),
('Directorate of Research and Development', 26),
('Directorate of Youth Development', 27),
('SERVICOM', 28),
('Health Services Department', 29),
('Directorate of Academic Planning', 30),
('Institute of Peace Studies & Conflict Management', 31),
('SIWES Directorates', 32),
('Students Affairs Division', 33),
('Abuja Liaison Office', 34),
('Academic Affairs Division', 35),
('Directorate of Sandwich Programme', 36),
('Directorate of Legal', 37),
('College of Postgraduate Studies', 38),
('School of Basic Studies', 39),
('Quality Assurance', 40),
('TSU Demonstration School', 41),
('Physical Planning Development Unit', 42),
('Works Department', 43),
('Diploma Unit', 44),
('Directorate of Sports', 45),
('Water Factory Unit', 46),
('Institute of Tree Crops and Research', 47),
('Bursary Unit', 48),
('Gen T.Y Danjuma College of Preliminary Studies, Takum', 49),
('Entrepreneurship Training Center, Donga', 50);
