---
deployment:
  tasks:
    - export DEPLOYPATH=/home/tsuniver/staff.tsuniversity.ng
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/cp -R * $DEPLOYPATH/
    - /bin/cp -R .htaccess $DEPLOYPATH/ 2>/dev/null || true
    - find $DEPLOYPATH -name "*.php" -exec chmod 644 {} \;
    - find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - chmod -R 755 $DEPLOYPATH/storage/ 2>/dev/null || true
    - chmod -R 755 $DEPLOYPATH/public/uploads/ 2>/dev/null || true
    - chmod -R 755 $DEPLOYPATH/storage/qrcodes/ 2>/dev/null || true
    - chmod 644 $DEPLOYPATH/public/.htaccess 2>/dev/null || true
    - rm -rf $DEPLOYPATH/.git* 2>/dev/null || true
    - rm -f $DEPLOYPATH/*.bat 2>/dev/null || true
    - rm -f $DEPLOYPATH/.cpanel.yml 2>/dev/null || true

